spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_chatroom?characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Azxc12388
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  # 添加以下配置 - 关键修复
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动映射

logging:
  pattern:
    console: "[%-5level] %msg%n"